name: mcdsm

services:

  mcdsm:
    image: mcdsm:latest
    build: .
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/app/networks:/networks
      - ./api/app/resources:/resources
    environment:
      - NETWORKS_DIR=/networks
      - RESOURCES_DIR=/resources
